> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here

An short introduction about PyTorch and about the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.poisson(input, generator=None)

Regenerate the tensor via poission distribution

Parameters:

input (Tensor) – the input tensor containing the rates of the Poisson distribution

generator (torch.Generator, optional) – a pseudorandom number generator for sampling

In [3]:
# Example 1 - working (change this)
numbers=torch.tensor([[1, 2], [3, 4.]])
torch.poisson(numbers)

tensor([[0., 3.],
        [2., 7.]])

Regenerate given integer tensor

In [8]:
rates = torch.rand(4, 4) * 5  # rate parameter between 0 and 5
print(rates)
torch.poisson(rates)

tensor([[0.0299, 4.7903, 2.1471, 2.3098],
        [3.1266, 0.7673, 0.7152, 3.8741],
        [1.0392, 3.8037, 0.4117, 1.4577],
        [3.4352, 0.3071, 0.8692, 0.1889]])


tensor([[0., 5., 1., 3.],
        [3., 0., 0., 6.],
        [0., 2., 2., 3.],
        [4., 0., 0., 0.]])

Regenerate generated random tensor

In [11]:
rates_tens = torch.tensor([[4.1237, 1.8373, 3.2343],[2.3344, 3.3324, 1.3378], [3.2349, 2.4447, 4.5269]])
torch.poisson(rates_tens)

tensor([[6., 0., 6.],
        [2., 3., 2.],
        [5., 3., 5.]])

Regenerate given float tensor



The Poisson distribution is usually used for modeling the number of times an event occurs in an interval of time or space.


Let's save our work using Jovian before continuing.

In [12]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 3.0 MB/s 


In [13]:
import jovian

In [14]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

Creates one dimensional, size = step whose values are evenly spaced from start and end base.

Paramaters :


        start (float) – the starting value for the set of points

        end (float) – the ending value for the set of points

        steps (int) – size of the constructed tensor

        base (float, optional) – base of the logarithm function. Default: 10.0.

Arguments:



        out (Tensor, optional) – the output tensor.

        dtype (torch.dtype, optional) – the data type to perform the computation in. Default: if None, uses the global default dtype (see torch.get_default_dtype()) when both start and end are real, and corresponding complex dtype when either is complex.

        layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.

        device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.

        requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.





In [15]:
torch.logspace(0, 10, 7)

tensor([1.0000e+00, 4.6416e+01, 2.1544e+03, 1.0000e+05, 4.6416e+06, 2.1544e+08,
        1.0000e+10])

Create one dimensional torch; size = 7 and base =10

In [16]:
torch.logspace(3, 10, 5, base=2)

tensor([   8.0000,   26.9087,   90.5097,  304.4370, 1024.0000])

Create one dimensional torch; size = 5 and base =2

In [21]:
torch.logspace(3,10,5,base=2,dtype=int)

tensor([   8,   26,   90,  304, 1024])

Create one dimensional torch; size = 5 and base =2 and data type is integer

When using this function, you can generate the one dimensional torch. In this torch, dtype, start-end point, size and more options can being modified by the users. Also the torch is generated as logaritmic.



In [22]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - torch.full_like(input, fill_value, \*, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)

Function return a new array with the same shape and type as a given torch.


Parameters :

        input (Tensor) – the size of input will determine size of the output tensor.

        fill_value – the number to fill the output tensor with.


Arguments :

        dtype (torch.dtype, optional) – the desired data type of returned Tensor. Default: if None, defaults to the dtype of input.

        layout (torch.layout, optional) – the desired layout of returned tensor. Default: if None, defaults to the layout of input.

        device (torch.device, optional) – the desired device of returned tensor. Default: if None, defaults to the device of input.

        requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

        memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.preserve_format.



In [23]:
rates_tens = torch.tensor([[4.1237, 1.8373, 3.2343],[2.3344, 3.3324, 1.3378], [3.2349, 2.4447, 4.5269]])

torch.full_like(rates_tens,5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

Regenerate the given torch as 5 

In [34]:
rates_tens = torch.tensor([[4.1237, 1.8373, 3.2343],[2.3344, 3.3324, 1.3378], [3.2349, 2.4447, 4.5269]])

torch.full_like(rates_tens[0:2],5,dtype=int)

tensor([[5, 5, 5],
        [5, 5, 5]])

Regenerate the given torch's [0:2] as 5 

In [36]:
rates_tens = torch.tensor([[4.1237, 1.8373, 3.2343],[2.3344, 3.3324, 1.3378], [3.2349, 2.4447, 4.5269]])

torch.full_like(rates_tens[:,1:2],0,dtype=int)

tensor([[0],
        [0],
        [0]])

Regenerate the given torch's [:,1:2] as integer 0 

You can regenerate the torch as what you want. However, the best uses area is boolean or 0-1 padding. 

In [38]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 -  torch.Tensor.view(*shape)

Returns a new tensor called view tensor, view tensor shares the same storage with the original tensor, view tensor's shape can be different from original tensor.


In [46]:
t = torch.randn(5,3,2)
t
t2 = t.view(5,6)
t2

tensor([[ 9.2333e-01,  7.2786e-01,  8.2120e-02, -1.6131e+00, -8.5079e-01,
         -1.6466e+00],
        [-1.1021e-02, -9.6561e-01, -7.5146e-01, -7.7894e-01, -2.5624e+00,
          2.1994e-01],
        [-2.7341e-01, -8.7429e-01, -1.3059e+00, -2.6084e+00,  3.4342e-01,
         -1.7668e+00],
        [-5.3424e-02,  2.5129e-01,  6.6230e-02,  9.5141e-01, -1.5337e+00,
          3.7720e-02],
        [ 8.8728e-01,  2.9656e+00,  7.3471e-01, -9.2928e-02, -1.6138e-03,
          2.6200e-01]])

Create a new torch.Tensor object with different size


In [47]:
t2[0,0] = 1
t

tensor([[[ 1.0000e+00,  7.2786e-01],
         [ 8.2120e-02, -1.6131e+00],
         [-8.5079e-01, -1.6466e+00]],

        [[-1.1021e-02, -9.6561e-01],
         [-7.5146e-01, -7.7894e-01],
         [-2.5624e+00,  2.1994e-01]],

        [[-2.7341e-01, -8.7429e-01],
         [-1.3059e+00, -2.6084e+00],
         [ 3.4342e-01, -1.7668e+00]],

        [[-5.3424e-02,  2.5129e-01],
         [ 6.6230e-02,  9.5141e-01],
         [-1.5337e+00,  3.7720e-02]],

        [[ 8.8728e-01,  2.9656e+00],
         [ 7.3471e-01, -9.2928e-02],
         [-1.6138e-03,  2.6200e-01]]])

Verify storage sharing feature

In [49]:
t.view(5,6) == t.view(5,6)

t.view(5,6) is t.view(5,6)



False

Verify a new torch.Tensor is generated by every .view() call


Closing comments about when to use this function

In [50]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - normal_(mean=0, std=1, *, generator=None)

In-place version of torch.normal()

Fills self tensor with elements samples from the normal distribution parameterized by mean and std.

In [51]:
t = torch.Tensor(3, 3)
t.normal_() # Tensor.normal_(mean=0, std=1) 

tensor([[ 0.5048, -0.6318, -0.2326],
        [-1.7804, -0.9126, -2.0034],
        [-1.1425, -0.6389, -0.2205]])

It creates a standard normal distribution with mean =0 and std=1


In [53]:
torch.empty(5).normal_(mean=4,std=0.5)

tensor([3.8186, 3.5840, 4.2089, 3.6279, 3.4345])

It create a matrix Z (a 1d tensor) of dimension 1 × 5, filled with random elements samples from the normal distribution parameterized by mean = 4 and std = 0.5.

In [54]:
torch.empty(2).normal_(mean=2,std=1.5)

tensor([0.3066, 2.6217])

t create a matrix Z (a 1d tensor) of dimension 1 × 2, filled with random elements samples from the normal distribution parameterized by mean = 2 and std = 1.5.

It helps to create standard normal distribution


In [56]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

These are the 5 statistical PyTorch function that I find interesting as discussed above.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* www.geeksforgeeks.org

In [57]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
